### ISSUE TITLE
Progress notification doesn’t show snapshot

### ISSUE THREAD

**Issue by 00ihsan** [gdombiak/OctoPrint-OctoPod#118]
The only progress notification that shows a snapshot is print complete. The rest is just text.

**Comment by gdombiak** [comment]
Hey @00ihsan , are you still seeing this issue? I'm looking at the code and it should be working fine but the good news is that I found another problem that is going to be fixed for next release :D

**Comment by gdombiak** [comment]
I know what is going on.... I will include the fix for next release. I'm sure there was an error in the logs
