### ISSUE TITLE
Web camera wont connect 

### ISSUE THREAD

**Issue by Cesar0415** [gdombiak/OctoPrint-OctoPod#12]
Request Error HTTP response 404

**Comment by gdombiak** [comment]
Hi Cesar,

The camera URL (address) seems to be pointing to the wrong place. What is the URL it is trying to reach? Are you on the same network?

**Comment by gdombiak** [comment]
Have you tried manually copying the camera URL and open that address on the browser? The default value works for people using octopi

**Comment by Cesar0415** [comment]
When I type it in manually it doesn’t seem to work but when I test it on
the octopi interface it’s fine

**Comment by gdombiak** [comment]
Cesar, hablas español?

What do you get when you paste the camera URL in the browser?

What does it mean to test on the octopi interface? How are you testing things?

**Comment by gdombiak** [comment]
Cesar, I'm closing this ticket due to inactivity. We can open a new one if you are still running into this issue.

Thanks,
Gaston
