### ISSUE TITLE
Thermal Runaway Warning Spam during M600 Pause

### ISSUE THREAD

**Issue by colwellkr** [gdombiak/OctoPrint-OctoPod#126]
Hello!

I just wanted to report that I believe the recent changes to thermal runaway detection have cause the Octopod notifications to start spamming thermal runaway notifications while paused for M600 (hot end cools down but the "setting" is still technically higher because it's waiting on the user).

If you need logs, please let me know where to find them and I can initiate and M600 to wait on it.

I don't think this is an issue during normal pauses because the target temperature gets dropped and the actual temp goes to match.

**Comment by gdombiak** [comment]
Thanks guys for this bug report. I need some time to fix this since I will have to test on the physical printer to reproduce and confirm fix is working correctly. Might work on this this weekend or following next one.

Regards,
Gaston
