### ISSUE TITLE
FR: Nozzle Temp alert

### ISSUE THREAD

**Issue by RafeAldridge** [gdombiak/OctoPrint-OctoPod#13]
Hi,

I can turn my printer on/off remotely. I often leave my printer to cool down whilst I'm elsewhere. I don't like to turn the printer off until the nozzle has cooled.

Therefore a notification similar to the bed temperature but for the nozzle would be fantastic.

I could leave the printer to cool, go away and then shut the power down when it's cooled. 

Thanks for a great plugin.

**Comment by gdombiak** [comment]
Great idea. Scheduled for next release.

**Comment by RafeAldridge** [comment]
Thanks!
