### ISSUE TITLE
SoC temp notification causes print cancellation

### ISSUE THREAD

**Issue by DanielDC88** [gdombiak/OctoPrint-OctoPod#141]
The option to notify you when the SoC reaches a threshold cancels the stops the print currently running, but this isn’t stated anywhere and Octoprint doesn’t contain any errors, so I can only assume this is unintentional.

**Comment by gdombiak** [comment]
Hi @DanielDC88,

This plugin only sends notifications and has no functionality to start/pause/cancel prints. I wonder what else could be happening that may be cancelling the print. Have you checked in OctoPrint's logs? If nothing there then I would suggest posting this issue in OctoPrint's forum. You might have better luck over there.

Sorry for not being of much help. I can say though that this plugin is not the reason the print got cancelled. 

Gaston
