### ISSUE TITLE
Not an issue...

### ISSUE THREAD

**Issue by paulpenney** [gdombiak/OctoPrint-OctoPod#16]
Just wanted to say - THANK YOU for developing this link. It works great for me and I use it every day, multiple times a day, on my iPad iPhone and watch while managing my three printers and their respective jobs. Thanks a lot.

**Comment by gdombiak** [comment]
Thanks Paul. Your message means a lot to me and is the reason and fuel that keeps me going on this hobby. Thank you for using OctoPod!
