### ISSUE TITLE
Notifications at specific heights

### ISSUE THREAD

**Issue by Mark9264** [gdombiak/OctoPrint-OctoPod#163]
Hi Gaston,

I'm a huge fan of your plugin and love using it.

I use layer notifications feature on the app to be notified at specific layers for current print jobs. 
I would like to see this added as a feature to the web ui. Essentially the same as you have now but the ability to set a persistent layer notification for every print.

For example i would like to have a notification on every print at layer 3, but not layers 1 and 2. I hope i've explained that well enough.

Thank you for reading, again i love the work you do. Good Job!

**Comment by gdombiak** [comment]
Thanks @Mark9264. I will add this to the next release
