### ISSUE TITLE
Notification Server not working

### ISSUE THREAD

**Issue by gary-wlg** [gdombiak/OctoPrint-OctoPod#171]
The notification server http://octopodprint.com is not working.  This is causing octoprint to hang anytime a notification tries to send out.

**Comment by gdombiak** [comment]
On it! Thanks for letting me know @gary-wlg . Updating certs so it's back online asap. Will post once fixed

**Comment by gary-wlg** [comment]
Thanks so much, appreciate the quick response.

Gary

Sent from my iPhone

On Oct 13, 2023, at 1:35 PM, Gaston Dombiak ***@***.***> wrote:

﻿

On it! Thanks for letting me know @gary-wlg<https://github.com/gary-wlg> . Updating certs so it's back online asap. Will post once fixed

**Comment by gdombiak** [comment]
All good to go now!!! Thanks again for letting me know and ping me if you run into anything else.

Gaston

**Comment by gary-wlg** [comment]
Thanks Again Gaston, I can confirm it is now working.

Have a great day!
Gary

Sent from my iPhone

On Oct 13, 2023, at 2:04 PM, Gaston Dombiak ***@***.***> wrote:

﻿

All good to go now!!! Thanks again for letting me know and ping me if you run into anything else.

Gaston
