### ISSUE TITLE
Notifications don't seem to be working

### ISSUE THREAD

**Issue by gary-wlg** [gdombiak/OctoPrint-OctoPod#172]
It appears that notifications are not working, I receive a send failed when trying to test the notifications.

**Comment by gdombiak** [comment]
Indeed it's not working again. Today I completely rebuilt the service and was working well ...... for a few hours it seems. :( Looking to see what's going on.

Thanks,
Gaston

**Comment by gary-wlg** [comment]
Thanks Gaston. I did notice that it didn't hang OctoPrint anymore, it just gave the error quickly and continued on - which is a definite improvement :)

**Comment by gdombiak** [comment]
Honestly, we got lucky! This is another kind of error that luckily does not block OctoPrint.

**Comment by gary-wlg** [comment]
I'll take luck any day!  I have 30 printers running this, I don't think I could live without these notifications :)

**Comment by gdombiak** [comment]
And we are back in business!!! One of the services was not correctly restarting when AWS instance was rebooted. All good now.

Thanks again for letting me know about this.
Gaston
