### ISSUE TITLE
Sponsor issue

### ISSUE THREAD

**Issue by Btyler12000** [gdombiak/OctoPrint-OctoPod#180]
Hello Gaston,
I made a contribution but when I opened the Octopod app, it started a new 14 day trial. 
Thanks, Brad Tyler
btyler12000@gmail.com

**Comment by gdombiak** [comment]
Hi Brad,

Thanks for becoming a Sponsor of OctoPod. Could you share a screenshot of the trial you are referring to? OctoPod has no concept of a trial or any commercial aspect to it. I'm curious what is it that you are seeing.

Thanks,
Gaston

**Comment by Btyler12000** [comment]
My mistake, it was Octoeverywhere that had the trial. Thanks for getting
back to me and congratulations on a great app.
