### ISSUE TITLE
I have tried to install using the Plugin Manager and Manually

### ISSUE THREAD

**Issue by dwcservices** [gdombiak/OctoPrint-OctoPod#20]
I get this message at the end of the installation "Error!Could not parse output from pip, see plugin_pluginmanager_console.log for generated output"

**Comment by chastonayb** [comment]
Hello i see that y have the same probleme with python2.7
[plugin_pluginmanager_console.log](https://github.com/gdombiak/OctoPrint-OctoPod/files/3587617/plugin_pluginmanager_console.log)
[octoprint.log](https://github.com/gdombiak/OctoPrint-OctoPod/files/3587618/octoprint.log)


but not find too fix

**Comment by chastonayb** [comment]
i put the libjpeg -dev

and now i works 

Super best regards.

**Comment by gdombiak** [comment]
@dwcservices are you still running into this issue?

**Comment by chastonayb** [comment]
No 

I tried your thing and it worked
your app works great
thank you for your help

**Comment by gdombiak** [comment]
Excellent. Great to hear that. Closing ticket then. 

Enjoy
Gaston
