### ISSUE TITLE
[Feature Request] Send notification at different progress %

### ISSUE THREAD

**Issue by simpat1zq** [gdombiak/OctoPrint-OctoPod#34]
Is there any way to have OctoPod send a notification periodically while a print is ongoing? Like send an update pic every X seconds. Maybe even as a premium feature to cover your push notify hosting costs?

**Comment by gdombiak** [comment]
HI @simpat1zq ,

Thanks for placing this request. Let me check into this and run some numbers based on current traffic to see what would be the economic impact (if any). I work hard to keep this project free and would like to keep it this way (as long as possible). Been paying the hosting out of my pocket until AWS accepted to sponsor hosting for this year.

Would sending a notification for this milestones work for you: 25%, 50%, 75%, 100%?

**Comment by gdombiak** [comment]
Good news. I checked network traffic and increasing frequency of notifications won't imply a jump in $$$. :) At least not from network traffic. I think that CPU and memory should hold fine too. I will make this feature an opt-in just in case.

Here is how network traffic has been growing over time. I think we will be close to 60GB of traffic.

![Screen Shot 2020-03-01 at 9 34 29 PM](https://user-images.githubusercontent.com/1791267/75648307-98b75e00-5c04-11ea-9d65-841d7fa08736.png)

**Comment by gdombiak** [comment]
Hi @simpat1zq, just finished implementing your requested feature. Let me know if you would like to help test it.

Thanks,
Gaston

**Comment by simpat1zq** [comment]
Yes. I can help test. Thank you.

**Comment by gdombiak** [comment]
Thanks @simpat1zq . You will need to install the development version of the plugin. Use this URL: https://github.com/gdombiak/OctoPrint-OctoPod/archive/dev.zip

Under Settings you will now see the option to choose progress notifications. See
![Screen Shot 2020-03-21 at 8 12 47 AM](https://user-images.githubusercontent.com/1791267/77229537-dd6f4e80-6b4b-11ea-9796-f7666dce4103.png)
