### ISSUE TITLE
Notification Sound

### ISSUE THREAD

**Issue by Printjunkie** [gdombiak/OctoPrint-OctoPod#47]
Hi,

i have no sound for notification. The notification arrives but without sound, I have already checked all settings on the Android system. What could that be?

Thank you

**Comment by gdombiak** [comment]
Hi @Printjunkie, this plugin is for iOS devices. The Android version of this plugin is [OctoPrint-Printoid](https://github.com/anthonyst91/OctoPrint-Printoid). You might want to [contact the developer](https://printoid.net/contact/) of that plugin for this issue.
