### ISSUE TITLE
[FR] Support for Custom Control Editor 

### ISSUE THREAD

**Issue by DominikPalo** [gdombiak/OctoPrint-OctoPod#49]
It would be great to support also [Custom Control Editor](https://plugins.octoprint.org/plugins/customControl/) plugin, so we can access custom controls/buttons created using this plugin from the OctoPod UI :)

**Comment by DominikPalo** [comment]
Sorry, I've just found that these controls are available by swiping the bottom part of the Panel view and this is also not the correct repository for the mobile app, so closing this request :)

**Comment by gdombiak** [comment]
Glad you found it!
