### ISSUE TITLE
IFTTT support

### ISSUE THREAD

**Issue by Jeggo65** [gdombiak/OctoPrint-OctoPod#52]
Hello,

it would be a very nice feature, if the octopod plugin could send IFTTT WebHook request for the messages it creates. E.g. if the temperature alert/message is send, IFTTT could issue an action via WebHook and turn off the power switch.
There is already an IFTTT plugin for octoprint, bit this could only issue requests for the standard octoprint events (PrintDone, PrintFailure etc.).

CU

Jens

**Comment by gdombiak** [comment]
Cool idea @Jeggo65 . I will check out how to implement this.
