### ISSUE TITLE
Remote access

### ISSUE THREAD

**Issue by Myrddinwylit** [gdombiak/OctoPrint-OctoPod#55]
I am getting notifications fine, and the app works great when I am inside the same network as the OctoPrint. Once I leave that network the notifications still work but cannot see or access the OctoPrint. 

The documentation says can connect from anywhere.

**Comment by greetoz** [comment]
You will need to do a portforward in your router to the octoprint server (port 80 or 443 if SSL is used).. Or VPN to your home network.

**Comment by gdombiak** [comment]
As @greetoz mentioned, you will need to either use _port forward + reverse proxy for secuirity_ or [setup your VPN](https://github.com/gdombiak/OctoPod/wiki/Using-OpenVPN-for-Remote-Access) which sounds harder than it actually is.
