### ISSUE TITLE
Delay snapshot/100% message

### ISSUE THREAD

**Issue by greetoz** [gdombiak/OctoPrint-OctoPod#56]
Thanks for the great plugin. I have a Prusa Mini with a pi camera on the X axis stepper motor. Problem is the prusa sends the extruder to the steppermotor when finished then i get a snapshot of the extruder haha. I have a custom Gcode which sends the extruder to the other side but the snapshot gets taken to early.

I would like a feature to delay the 100%/Snapshot by x seconds to let the extruder get out of the way.

**Comment by gdombiak** [comment]
Interesting request. Will schedule it for a future release. Thanks for sharing this idea.

Gaston
