### ISSUE TITLE
IFTTT Documentation

### ISSUE THREAD

**Issue by shatteredsite** [gdombiak/OctoPrint-OctoPod#71]
It would be extremely helpful to also include documentation on creating an example IFTTT applet.

**Comment by gdombiak** [comment]
Hi @shatteredsite , I just created [this documentation page](https://github.com/gdombiak/OctoPrint-OctoPod/wiki/How-to-use-IFTTT%3F) for your request. Let me know if that helped and if I need to clarify any text. I quickly wrote it down to help with your request.

Regards,
Gaston

**Comment by gdombiak** [comment]
Closing since I added new documentation for how to use IFTTT and this plugin. We can reopen if something else is needed.
