### ISSUE TITLE
Push notification thumbnail for iPhone upside down

### ISSUE THREAD

**Issue by jghake** [gdombiak/OctoPrint-OctoPod#74]
I have two cameras set up, a raspberry pi camera on port 8080, and an emeet webcam on 8081. I've set the snapshot URL properly for the emeet but the thumbnails on my phone are upside down while the camera view is not in OctoPrint.
![2021-01-15 19 18 08](https://user-images.githubusercontent.com/15810575/104797290-cf8d5880-5771-11eb-9f29-bf89bef8f7d7.png)

**Comment by gdombiak** [comment]
Thanks @jghake for sharing this. I think I know what is happening. I do not think I implemented image rotation. Since you can use the URL of any camera .... I will add new buttons to rotate the image in the plugin configuration. I cannot rely on OctoPrint's configuration for this.

Thanks,
Gaston

**Comment by gdombiak** [comment]
@jghake are you using OctoPrint's camera with this plugin? I checked the code and I see that the plugin will rotate/flip the image according to the settings you have in here:

![Screen Shot 2021-01-17 at 11 42 17 AM](https://user-images.githubusercontent.com/1791267/104853953-0fab2300-58b9-11eb-8c13-d608f4aae763.png)

Is that not working for you? I will still do this improvement since I think the flip/rotate settings should be independent since you can set any URL for the notification thumbnail.

Gaston

**Comment by jghake** [comment]
Here is my camera configuration. I'm using the secondary emeet 960 as the notification URL.

![image](https://user-images.githubusercontent.com/15810575/104857841-011c3600-58d0-11eb-978a-1b53c206f95d.png)

![image](https://user-images.githubusercontent.com/15810575/104857852-13966f80-58d0-11eb-8603-07052f1ed656.png)

**Comment by freilich** [comment]
The "flip" flags in OctoPrint only affect the OctoPrint UI.  If you go to the raw stream (/webcam/?action=stream) it will be the natural orientation of the camera, which is likely why the thumbnail is not correct.

**Comment by jghake** [comment]
The thing is it isn't upside down.


![image](https://user-images.githubusercontent.com/15810575/104859959-ae497b00-58dd-11eb-97b1-55f65fc891ea.png)

**Comment by freilich** [comment]
I think I see the issue.  You have two cameras, the first one needs to be flipped but the second one doesn't, right?   Looks like the code doesn't differentiate between them, it just sees that you have the checkboxes marked to flip so it flips the thumbnail.  Editing /boot/octopi.txt to flip the camera, then unchecking the boxes in the UI should solve the issue for you.

**Comment by jghake** [comment]
Tried this and all is well.

**Comment by gdombiak** [comment]
Added new configuration so you can control flip/rotation for whatever camera you are using.

![Screen Shot 2021-01-24 at 12 27 16 PM](https://user-images.githubusercontent.com/1791267/105642597-81e2b100-5e3f-11eb-81bd-9d35c04dd46a.png)

**Comment by gdombiak** [comment]
FYI, new release is out that now let's you flip/rotate cameras from the plugin settings page
