### ISSUE TITLE
No snapshot at 50% Version 0.3.0

### ISSUE THREAD

**Issue by Jack77777777** [gdombiak/OctoPrint-OctoPod#80]
I have configured to get notifications at 50 and 100%. Since 0.3.0 50% includes no snapshot. 100% does

**Comment by Jack77777777** [comment]
@gdombiak is this a bug or a feature ?

**Comment by gdombiak** [comment]
Hi @Jack77777777 , not a feature for sure. :) I made some changes in that area of the code in the last release so will check out what is going on. Thanks for letting me know.

Gaston

**Comment by Jack77777777** [comment]
@gdombiak Do you have a release date for 0.3.1 ?

**Comment by gdombiak** [comment]
Hey @Jack77777777, just to confirm, you are getting the notification at 50% but it does not include a camera snapshot? Is this happening always? Sounds similar to https://github.com/gdombiak/OctoPrint-OctoPod/issues/118

**Comment by gdombiak** [comment]
I know what is going on.... I will include the fix for next release. I'm sure there was an error in the logs
