### ISSUE TITLE
Suppress a notification 

### ISSUE THREAD

**Issue by ingo916** [gdombiak/OctoPrint-OctoPod#81]
I use TP-Link smart outlet to turn off power to my printer but octoprint is on a different outlet and never shuts off. However octoprint detects the serial connection as down and generates a notification. After installing octopod I get many many sms messages

is there a way to suppress theses alerts/push notifications from octopod?
 
![73EEEABB-EE6F-42AB-A786-576EAFC8E46E](https://user-images.githubusercontent.com/41309095/108612431-8eeeb380-739d-11eb-884a-b0c48afc0d40.jpeg)

**Comment by tibmeister** [comment]
Yes, I am having this issue to where it's spamming my phone and watch, about 2 per minute.  This is new behavior and will annoy me to no end.

**Comment by ingo916** [comment]
I resolved the issue by removing the tape I added to the +5v on the usb plug that attaches to my printer and raspberry pi.

**Comment by taclane** [comment]
The error is generated by Octoprint itself when it fails to automatically connect to a printer, usually after a reboot.  I'm not sure if there's an easy way for the Octopod plugin to separate out this particular error from others it receives from Octoprint.

If you are using the TP Link plugin, an easy way to stop this notification it is to disable the Octoprint auto-connect, and let the plugin handle connect/disconnect.
<img width="468" alt="octoprint-auto" src="https://user-images.githubusercontent.com/12748062/112490467-c44c3f80-8d55-11eb-8039-45383fea86a2.png">

<img width="545" alt="tplink-connection" src="https://user-images.githubusercontent.com/12748062/112490534-d332f200-8d55-11eb-975f-b1dab175416d.png">

Alternatively, if you want to leave Octoprint auto-connect enabled, you can do a quick edit to `/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/comm.py` around line 3265 to comment out the error, and flag the printer as offline instead.
```python
#        error_text = "No more candidates to test, and no working port/baudrate combination detected."
#        self._trigger_error(error_text, "autodetect")
        self._changeState(self.STATE_CLOSED)
```
(whitespace is important, there are 8 spaces in front of self._changeState)
