### ISSUE TITLE
Camera frozen when opening app via notification 

### ISSUE THREAD

**Issue by bls8486** [gdombiak/OctoPrint-OctoPod#86]
If I open the app via the icon, the video stream has no issues. If I click the notification, all data loads but the camera is frozen.

**Comment by gdombiak** [comment]
Thanks @bls8486 for reporting this issue. This has been fixed for the next release of OctoPod. https://github.com/gdombiak/OctoPod/issues/474

**Comment by bls8486** [comment]
I would like to re-open this as it still happens.
