### ISSUE TITLE
The printoid plugin is not installed in octoprint

### ISSUE THREAD

**Issue by lex007112** [gdombiak/OctoPrint-OctoPod#90]
I can not install the printoid plugin in octoprint, an error always pops up, the logs are attached, the application is purchased.
[plugin_pluginmanager_console.log](https://github.com/gdombiak/OctoPrint-OctoPod/files/6664209/plugin_pluginmanager_console.log)
[octoprint.log](https://github.com/gdombiak/OctoPrint-OctoPod/files/6664210/octoprint.log)

**Comment by gdombiak** [comment]
Hi @lex007112,

You might want to contact the Printoid developer regarding that plugin. The Printod plugin is a fork of this one and is maintained by another person.

Good luck!
Gaston
